### PR TITLE
fix: Retry PipelineRuns that fail due to a Tekton race condition

### LINKED ISSUE #5324: Race condition causes PipelineRun failure sporadically
1-2% of the time on the prod cluster, we see `PipelineRun`s fail with messages like this:
```
Pipeline jx/jenkins-x-jx-pr-5266-images-16 can't be found:pipeline.tekton.dev
      "jenkins-x-jx-pr-5266-images-16" not found
```
This seems to be a race condition in the `PipelineRun` controller where it gets informed of a new `PipelineRun` and tries to run it, but its lister cache doesn't yet have the corresponding `Pipeline`. I haven't yet managed to reproduce this effectively so can't figure out how to fix it properly in Tekton yet.

### PR DESCRIPTION
**Pull request by abayer**
If we see a particular string in the failure message for a
`PipelineRun`, we know it's due to a race condition in Tekton where
the `PipelineRun` starts getting handled by the controller but its
cache of `Pipeline`s doesn't yet contain the relevant `Pipeline`. So
when we see that, let's reset the `ProwJob` and delete the
existing-but-failed `PipelineRun`(s) so that we can retry.

fixes https://github.com/jenkins-x/jx/issues/5324

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

File: prow/cmd/pipeline/controller.go [hunk 1]
```diff
@@ -68,6 +68,10 @@ const (
 
 	// Abort pipeline run request which don't return in 5 mins.
 	maxPipelineRunRequestTimeout = 5 * time.Minute
+
+	// Error message that shows up in the PipelineRun status for a race condition where the Pipeline is not yet in the
+	// PipelineRun controller's lister when it tries to trigger the PipelineRun
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go:73]: Isn't this because of the cache latency? The pipeline is created but takes s a while until is available to the informers to pick it up.

File: prow/cmd/pipeline/controller.go [hunk 2]
```diff
@@ -521,20 +525,20 @@ func reconcile(c reconciler, key string) error {
 		if err != nil {
 			return fmt.Errorf("no pipelinerun found with name %s: %v", name, err)
 		}
-		prowJob := p.Labels[prowJobName]
-		if prowJob == "" {
+		prowJobName := p.Labels[prowJobName]
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go]: I think this is overwriting the `prowJobName` constant in this scope. This constant is the label name used in the selector.

File: prow/cmd/pipeline/controller.go [hunk 3]
```diff
@@ -521,20 +525,20 @@ func reconcile(c reconciler, key string) error {
...
 		}
 
-		pj, err = c.getProwJob(prowJob)
+		pj, err = c.getProwJob(prowJobName)
 		if err != nil {
 			return fmt.Errorf("no matching prowjob for pipelinerun %s: %v", name, err)
 		}
 
-		selector := fmt.Sprintf("%s = %s", prowJobName, pj.Name)
+		selector := fmt.Sprintf("%s = %s", prowJobName, name)
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go]: I think his selector is incorrect (see the comment above):
`prowJobName` contains now the prow jobs name not the label name
`name` is the pipelinerun name in this context not the effective prowjob name 

The PipelineRun used to have a label of this form:
```
prowJobName: "name of the prow job"
```
now the value of the selector is:
```
"name of the prow job": "name of the pipelinerun"
```

File: prow/cmd/pipeline/controller.go [hunk 4]
```diff
@@ -613,24 +617,39 @@ func reconcile(c reconciler, key string) error {
...
+			// If the pipeline failed due to the known race condition, wipe the status and retry.
+			npj.Status = prowjobv1.ProwJobStatus{
+				StartTime: c.now(),
+				State:     prowjobv1.TriggeredState,
+			}
+			// Delete the existing PipelineRun(s) so that we don't get confused by them in subsequent reconciliation.
+			for _, r := range runs {
+				logrus.Infof("Delete pipelinerun: %s", r.Name)
+				if err := c.deletePipelineRun(context, namespace, r.Name); err != nil {
+					return fmt.Errorf("delete pipelinerun: %v", err)
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go:673]: This will lead to a reconciliation retry with the prow job in a different state. The next loop execution most likely won't cleanup the left pipeline runs. Is this error critical for completely the reconciliation loop?

File: prow/cmd/pipeline/controller.go [hunk 5]
```diff
@@ -613,24 +617,39 @@ func reconcile(c reconciler, key string) error {
...
 		npj := pj.DeepCopy()
-		if npj.Status.StartTime.IsZero() {
-			npj.Status.StartTime = c.now()
-		}
-		if npj.Status.CompletionTime.IsZero() && finalState(state) {
-			now := c.now()
-			npj.Status.CompletionTime = &now
+		if state == prowjobv1.FailureState && strings.Contains(msg, pipelineRunShouldRetryMessage) {
+			// If the pipeline failed due to the known race condition, wipe the status and retry.
+			npj.Status = prowjobv1.ProwJobStatus{
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go:662]: I would try to set up the `DeletionTImestamp` and let the normal loop to cleanup the pipelineruns and afterwards reset the status to retrigger. 

This routine is only meant to update the status and not really to do cleanups.

**Review by ccojocar — CHANGES_REQUESTED** [review]

File: prow/cmd/pipeline/controller.go (hunk 1 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go:73]: I believe that’s the case, yes. What I think is happening is that the `PipelineRun` informer triggers the reconciliation and finds the `PipelineRun` for the name at https://github.com/tektoncd/pipeline/blob/v0.5.2/pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go#L161, but then doesn’t find its `Pipeline` at https://github.com/tektoncd/pipeline/blob/v0.5.2/pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go#L234. I haven’t been able to figure out how exactly the relevant cache gets updated.

File: prow/cmd/pipeline/controller.go (hunk 2 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go]: Yeah, I need to roll this bit back.

File: prow/cmd/pipeline/controller.go (hunk 3 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go]: Same as above.

File: prow/cmd/pipeline/controller.go (hunk 4 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go:673]: Good question...we need to not see the “bad” run(s) on next reconciliation, so that it’ll create a new run and not just treat the old failure(s) as meaning the ProwJob has failed. If there’s a better way to do this than deleting the old run(s), I’m completely open to it.

File: prow/cmd/pipeline/controller.go (hunk 5 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go:662]: Ok, lemme figure that out.

File: prow/cmd/pipeline/controller.go (hunk 4 above)
Comment (ccojocar) [reply prow/cmd/pipeline/controller.go:673]: Let's try like this, and see how it works.

**Review by ccojocar — APPROVED** [review]
