### PR TITLE
fix: Use "build" label, not "build_id" param to find PR ID/number

### LINKED ISSUE #5394: Prow always thinks the build number is 1 (for build link) with metapipeline enabled
Most likely something's awry in the `pipeline` controller in Prow - it's not looking at the right place for the build number or something.

### PR DESCRIPTION
**Pull request by abayer**
Also update `pj.Status.BuildID` and `pj.Status.URL` if unset during
reconciliation.

fixes https://github.com/jenkins-x/jx/issues/5394

/assign @ccojocar 
/assign @hferentschik

### CODE REVIEW

File: prow/cmd/pipeline/controller.go [hunk 1]
```diff
@@ -867,6 +877,8 @@ func makePipelineRunWithPrefix(pj prowjobv1.ProwJob, buildID string, pr *pipelin
 		Name:  "build_id",
 		Value: buildID,
 	})
+	p.Labels["build"] = buildID
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go]: I would extract `build` into a const.

File: prow/cmd/pipeline/controller.go [hunk 2]
```diff
@@ -940,11 +952,10 @@ func (c *controller) requestPipelineRun(context, namespace string, pj prowjobv1.
 	return "", fmt.Errorf("no PipelineRun object found returned by pipeline runner")
 }
 
-func getBuildID(pr *pipelinev1alpha1.PipelineRun) string {
-	for _, param := range pr.Spec.Params {
-		if param.Name == "build_id" {
-			return param.Value
-		}
+func getBuildNumber(pr *pipelinev1alpha1.PipelineRun) string {
+	buildNum := pr.Labels["build"]
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go]: ditto

File: prow/cmd/pipeline/controller.go [hunk 3]
```diff
@@ -690,6 +690,16 @@ func updateProwJobState(c reconciler, pj *prowjobv1.ProwJob, state prowjobv1.Pro
 			}
 			npj.Status.State = state
 			npj.Status.Description = msg
+
+			// Set the status build ID and URL if they're empty
+			for _, r := range runs {
+				if npj.Status.BuildID != "" && npj.Status.URL != "" {
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go]: I would consider moving the if statement outside of `for`, it doesn't seem to be dependent on `r`.

File: prow/cmd/pipeline/controller.go [hunk 4]
```diff
@@ -690,6 +690,16 @@ func updateProwJobState(c reconciler, pj *prowjobv1.ProwJob, state prowjobv1.Pro
...
+					continue
+				}
+				logrus.Infof("Setting build ID and URL for ProwJob/%s from PipelineRun %s", pj.GetName(), r.Name)
+				npj.Status.BuildID = getBuildNumber(r)
```
Comment (ccojocar) [inline prow/cmd/pipeline/controller.go:699]: Isn't this going to set the build number of metapipline in case is the first run? Shouldn't be instead the build number of the effective pipeline?

File: prow/cmd/pipeline/controller.go (hunk 3 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go]: The reasoning here was to make sure we only do it once. =) But I'm fine with moving it.

File: prow/cmd/pipeline/controller.go (hunk 4 above)
Comment (abayer) [reply prow/cmd/pipeline/controller.go:699]: The metapipeline and effective pipeline always have the same build number.

**Comment by abayer** [comment]
Switch `build` to a const, and also added update-bot for `jenkins-x-charts/prow`.

**Comment by abayer** [comment]
and tweaked the `if` logic. =)

File: prow/cmd/pipeline/controller.go (hunk 4 above)
Comment (ccojocar) [reply prow/cmd/pipeline/controller.go:699]: great!

**Review by ccojocar — APPROVED** [review]

**Review by ccojocar — APPROVED** [review]
